# configuration for https://travis-ci.org/bitcoinj/bitcoinj
sudo: false
dist: trusty
language: java
jdk: oraclejdk8
install: true # remove default
script:
  - mvn -q clean install -Pno-network
  - jdk_switcher use openjdk7
  - cd core
  - mvn -q clean package -Pno-network

after_success:
  - cd ../core
  - mvn jacoco:report coveralls:report

notifications:
  irc:
    channels: "irc.freenode.net#bitcoinj"
    skip_join: true
