name: GraalVM Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        java: [ '17' ]
        graalvm: [ '22.1.0' ]
        gradle: ['7.6']
      fail-fast: false
    name: ${{ matrix.os }} JDK ${{ matrix.graalvm }}.${{ matrix.java }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.graalvm }}
          java-version: ${{ matrix.java }}
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ matrix.gradle }}
          arguments: test nativeCompile --info --stacktrace
      - name: Upload wallet-tool as artifact
        uses: actions/upload-artifact@v3
        with:
          name: wallet-tool-${{ matrix.os }}
          path: wallettool/build/native/nativeCompile/wallet-tool
